# Generated by Django 4.2.4 on 2023-08-31 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("Profile_pick", models.ImageField(null=True, upload_to="")),
                ("age", models.IntegerField(max_length=3, unique=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "male"), ("F", "female")],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("occupation", models.CharField(max_length=100, null=True)),
                ("is_married", models.BooleanField(default=False)),
                ("birth_date", models.DateField()),
                ("email", models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
