# Generated by Django 4.2.4 on 2023-08-31 10:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("memo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="age",
            field=models.IntegerField(max_length=30, unique=True),
        ),
    ]
