# Generated by Django 4.2.4 on 2023-09-02 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("memo", "0003_caste_fatherprofile_hobby_religion_sect_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="sect",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profiles",
                to="memo.sect",
            ),
        ),
    ]
